services:
  ollama:
    image: ollama/ollama:latest # 3.2
    container_name: ai-qa-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:

